export PATH='/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/sbin:/usr/sbin:/usr/bin:/usr/bin:/sbin:/sbin:/bin:/bin:/usr/bin/X11:/usr/bin/X11:/usr/games:/usr/games'
export TMPDIR='/tmp'
export PS1='%m%::%~ %n%# '	
umask 022

export EDITOR=/usr/bin/editor
export PAGER=/usr/bin/pager

for i in /etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        . $i
    fi
done
