#!/bin/bash
set -euo pipefail

PROJECT="$(cd "$(dirname "$0")/.." && pwd -P)"
ROOT="$(cd "$PROJECT/.." && pwd -P)"
RETURN_B="${DT_BUILD102739B_MODE:-0}"
RETURN_C="${DT_BUILD102739C_MODE:-0}"
RETURN_D="${DT_BUILD102739D_MODE:-0}"
RETURN_E="${DT_BUILD102739E_MODE:-0}"
RETURN_F="${DT_BUILD102739F_MODE:-0}"
RETURN_G="${DT_BUILD102739G_MODE:-0}"
RETURN_H="${DT_BUILD102739H_MODE:-0}"
RETURN_I="${DT_BUILD102739I_MODE:-0}"
RETURN_J="${DT_BUILD102739J_MODE:-0}"
DOPAMINE="${DOPAMINE:-$ROOT/Dopamine_Rootful-main}"
OPAINJECT_SRC="$DOPAMINE/BaseBin/opainject"
if [[ "$RETURN_J" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739J"
elif [[ "$RETURN_I" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739I"
elif [[ "$RETURN_H" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739H"
elif [[ "$RETURN_G" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739G"
elif [[ "$RETURN_F" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739F"
elif [[ "$RETURN_E" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739E"
elif [[ "$RETURN_D" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739D"
elif [[ "$RETURN_C" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739C"
elif [[ "$RETURN_B" == "1" ]]; then
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739B"
else
    DEFAULT_BUILD_ROOT="$PROJECT/build/102739A"
fi
BUILD_ROOT="${DT_BUILD_OUTPUT_ROOT:-$DEFAULT_BUILD_ROOT}"
OUT="$BUILD_ROOT/Handoff516"
OBJ="$BUILD_ROOT/obj/opainject"
THEOS_ROOT="${THEOS:-$HOME/theos}"
SYSROOT="${TVOS_SYSROOT:-$THEOS_ROOT/sdks/AppleTVOS16.4.sdk}"
LDID="${LDID:-/opt/local/bin/ldid}"
VTOOL="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/vtool"

expect_sha() {
    local path="$1" expected="$2" got
    got="$(shasum -a 256 "$path" | awk '{print $1}')"
    [[ "$got" == "$expected" ]] || {
        echo "SHA256 mismatch: $path" >&2
        echo "  expected $expected" >&2
        echo "  got      $got" >&2
        exit 1
    }
}

[[ -d "$PROJECT/build/102738Z/Handoff516" ]] || {
    echo "ERROR: missing frozen BUILD102738Z resources" >&2; exit 1;
}
expect_sha "$PROJECT/build/102738Z/Handoff516/dt_opainject516" \
  "0b7dcd9c7258d33e347c94258b57817d0a04fc163af855d3b21499598f6b48fb"
expect_sha "$PROJECT/build/102738Z/Handoff516/dt_jbctl516" \
  "6fcede5b98ee244106b9bc0b64e9da94fb3464e0bfe671f53a99485ee466c067"
expect_sha "$PROJECT/build/102738Z/Handoff516/libjailbreak.dylib" \
  "0ec9129c2b37c952794b4dd33efd5d5e2b9062cc72cf990947662baf3c519754"
expect_sha "$PROJECT/build/102738Z/Handoff516/libchoma.dylib" \
  "40ee6f87dcca7af63a8be1e9e185ff74ae2046cb97c3aa2405c6af6f29ae586b"

if [[ "$RETURN_J" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739J_CONTROLLED_REPLY_ROUNDTRIP_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
elif [[ "$RETURN_I" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739I_CONTROLLED_HANDLER_ABI_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
elif [[ "$RETURN_H" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739H_ARGUMENT_MARSHALLING_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
elif [[ "$RETURN_G" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739G_DOMAIN_ACTION_RESOLUTION_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
elif [[ "$RETURN_F" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739F_CALLER_IDENTITY_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
elif [[ "$RETURN_E" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739E_DICTIONARY_CLASSIFIER_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
elif [[ "$RETURN_D" == "1" ]]; then
    [[ -d "$PROJECT/build/102739C" ]] || {
        echo "ERROR: missing frozen BUILD102739C artifact foundation" >&2; exit 1;
    }
    rm -rf "$BUILD_ROOT"
    cp -R "$PROJECT/build/102739C" "$BUILD_ROOT"
elif [[ "$RETURN_C" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
elif [[ "$RETURN_B" == "1" ]]; then
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739B_RETURN_OBSERVER_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
else
    DT_BUILD102738Z_PERSISTENT_HOOK=1 \
    DT_BUILD102739A_OBSERVER_HOOK=1 \
    DT_BUILD_OUTPUT_ROOT="$BUILD_ROOT" \
      bash "$PROJECT/scripts/build102738y_got_wrapper_invocation.sh"
fi

rm -rf "$OBJ"
mkdir -p "$OBJ"
cp "$OPAINJECT_SRC"/dyld.m "$OPAINJECT_SRC"/shellcode_inject.m \
    "$OPAINJECT_SRC"/thread_utils.m "$OPAINJECT_SRC"/task_utils.m \
    "$OPAINJECT_SRC"/arm64.m "$OPAINJECT_SRC"/*.h "$OBJ/" 2>/dev/null || true
cp "$PROJECT/handoff681/dt_opainject681_rop_inject.h" "$OBJ/rop_inject.h"
cp "$PROJECT/handoff681/dt_opainject681_main.m" "$OBJ/main.m"
cp "$PROJECT/handoff681/dt_opainject681_rop_inject.m" "$OBJ/rop_inject.m"
cp "$PROJECT/handoff681/dt_opainject_tvos_prefix.h" "$OBJ/"

OBSERVER_DEFINES=()
if [[ "$RETURN_J" == "1" ]]; then
    echo "=== BUILD102739J controlled reply roundtrip + deterministic observer ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739D_DETERMINISTIC_TRIGGER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739E_DICTIONARY_CLASSIFIER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739F_CALLER_IDENTITY=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739G_DOMAIN_ACTION_RESOLUTION=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739H_ARGUMENT_MARSHALLING=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739I_CONTROLLED_HANDLER_ABI=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739J_CONTROLLED_REPLY_ROUNDTRIP=1 )
elif [[ "$RETURN_I" == "1" ]]; then
    echo "=== BUILD102739I controlled action handler ABI + deterministic observer ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739D_DETERMINISTIC_TRIGGER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739E_DICTIONARY_CLASSIFIER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739F_CALLER_IDENTITY=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739G_DOMAIN_ACTION_RESOLUTION=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739H_ARGUMENT_MARSHALLING=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739I_CONTROLLED_HANDLER_ABI=1 )
elif [[ "$RETURN_H" == "1" ]]; then
    echo "=== BUILD102739H read-only action argument marshalling + deterministic observer ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739D_DETERMINISTIC_TRIGGER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739E_DICTIONARY_CLASSIFIER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739F_CALLER_IDENTITY=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739G_DOMAIN_ACTION_RESOLUTION=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739H_ARGUMENT_MARSHALLING=1 )
elif [[ "$RETURN_G" == "1" ]]; then
    echo "=== BUILD102739G read-only domain/permission/action resolver + deterministic observer ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739D_DETERMINISTIC_TRIGGER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739E_DICTIONARY_CLASSIFIER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739F_CALLER_IDENTITY=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739G_DOMAIN_ACTION_RESOLUTION=1 )
elif [[ "$RETURN_F" == "1" ]]; then
    echo "=== BUILD102739F read-only caller identity hook + deterministic observer ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739D_DETERMINISTIC_TRIGGER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739E_DICTIONARY_CLASSIFIER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739F_CALLER_IDENTITY=1 )
elif [[ "$RETURN_E" == "1" ]]; then
    echo "=== BUILD102739E read-only dictionary classifier hook + deterministic observer ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739D_DETERMINISTIC_TRIGGER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739E_DICTIONARY_CLASSIFIER=1 )
elif [[ "$RETURN_D" == "1" ]]; then
    echo "=== BUILD102739D frozen 102739C hook + deterministic launchd trigger observer ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
    OBSERVER_DEFINES+=( -DDT_BUILD102739D_DETERMINISTIC_TRIGGER=1 )
elif [[ "$RETURN_C" == "1" ]]; then
    echo "=== BUILD102739C read-only output-contract observer helper rebuild ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739C_OUTPUT_CONTRACT_OBSERVER=1 )
elif [[ "$RETURN_B" == "1" ]]; then
    echo "=== BUILD102739B read-only post-original return observer helper rebuild ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739B_RETURN_OBSERVER=1 )
else
    echo "=== BUILD102739A read-only post-Wall-2 observer helper rebuild ==="
    OBSERVER_DEFINES+=( -DDT_BUILD102739A_OBSERVER=1 )
fi
xcrun -sdk appletvos clang \
    -arch arm64 -isysroot "$SYSROOT" -mtvos-version-min=14.0 -O2 \
    -Wno-deprecated-declarations -Wno-error -D_DARWIN_UNLIMITED_SYSCALLS \
    -DDT_BUILD102736C_TASKPORT_REPAIR=1 "${OBSERVER_DEFINES[@]}" \
    -include "$OBJ/dt_opainject_tvos_prefix.h" -I"$OBJ" \
    -I"$DOPAMINE/BaseBin/_external/include" \
    -framework CoreFoundation -framework Foundation -ldl \
    -Wl,-undefined,dynamic_lookup \
    -o "$OUT/dt_opainject516" \
    "$OBJ/main.m" "$OBJ/dyld.m" "$OBJ/shellcode_inject.m" \
    "$OBJ/rop_inject.m" "$OBJ/thread_utils.m" "$OBJ/task_utils.m" "$OBJ/arm64.m"
"$VTOOL" -set-build-version tvos 14.0 14.0 -replace \
    -o "$OUT/dt_opainject516" "$OUT/dt_opainject516"
"$LDID" -S"$PROJECT/handoff681/entitlements_opainject681.plist" "$OUT/dt_opainject516"
chmod +x "$OUT/dt_opainject516"

expect_sha "$OUT/dt_jbctl516" \
  "6fcede5b98ee244106b9bc0b64e9da94fb3464e0bfe671f53a99485ee466c067"
expect_sha "$OUT/libjailbreak.dylib" \
  "0ec9129c2b37c952794b4dd33efd5d5e2b9062cc72cf990947662baf3c519754"
expect_sha "$OUT/libchoma.dylib" \
  "40ee6f87dcca7af63a8be1e9e185ff74ae2046cb97c3aa2405c6af6f29ae586b"

HOOK="$OUT/launchdhook516.dylib"
HELPER="$OUT/dt_opainject516"
HOOK_STRINGS="$BUILD_ROOT/obj/hook/hook_strings.txt"
HELPER_STRINGS="$OBJ/helper_strings.txt"
strings "$HELPER" > "$HELPER_STRINGS"

if [[ "$RETURN_J" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739j_reply_telemetry'
    rg -q 'BUILD102739_IDENTITY_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739J_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739J_TRIGGER_PID=
        BUILD102739J_TRIGGER_EUID=
        BUILD102739J_TRIGGER_DOMAIN=
        BUILD102739J_TRIGGER_ACTION=
        BUILD102739J_TRIGGER_COUNT=1
        BUILD102739J_TRIGGER_TIMEOUT_GUARD_SECONDS=3
        BUILD102739J_TRIGGER_SEND_RC=
        BUILD102739J_TRIGGER_REPLY_IS_DICTIONARY=
        BUILD102739J_TRIGGER_REPLY_ROOT_PATH_EXISTS=
        BUILD102739J_TRIGGER_REPLY_ROOT_PATH_TYPE_STRING=
        BUILD102739J_TRIGGER_REPLY_ROOT_PATH_MATCH=
        BUILD102739J_TRIGGER_REPLY_RESULT_EXISTS=
        BUILD102739J_TRIGGER_REPLY_RESULT_TYPE_INT64=
        BUILD102739J_CLIENT_REPLY_RELEASE_DELTA=1
        BUILD102739J_ORIGINAL_RECEIVE_CALL_DELTA=
        BUILD102739J_ORIGINAL_RECEIVE_RETURN_DELTA=
        BUILD102739J_WRAPPER_RETURN_22_DELTA=
        BUILD102739J_SERVER_COMMITTED_LIFECYCLE_PASS_DELTA=
        BUILD102739J_CONTROLLED_REPLY_ROUNDTRIP=PASS
    )
elif [[ "$RETURN_I" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739i_handler_telemetry'
    rg -q 'BUILD102739_IDENTITY_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739I_OBSERVER_MODE=READ_ONLY
        BUILD102739I_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739I_TRIGGER_PID=
        BUILD102739I_TRIGGER_EUID=
        BUILD102739I_TRIGGER_DOMAIN=
        BUILD102739I_TRIGGER_ACTION=
        BUILD102739I_TRIGGER_COUNT=1
        BUILD102739I_TRIGGER_TIMEOUT_GUARD_SECONDS=3
        BUILD102739I_TRIGGER_SEND_RC=
        BUILD102739I_ENTRY_DELTA=
        BUILD102739I_RETURN_DELTA=
        BUILD102739I_HANDLER_INVOCATION_DELTA=
        BUILD102739I_MARSHALLING_COMPLETE_DELTA=
        BUILD102739I_HANDLER_CALL_ATTEMPT_DELTA=
        BUILD102739I_HANDLER_RETURN_DELTA=
        BUILD102739I_HANDLER_ARG0_OUTPUT_SLOT_MATCH_DELTA=
        BUILD102739I_HANDLER_ARGS1_THROUGH_7_NULL_DELTA=
        BUILD102739I_HANDLER_OUTPUT_WRITE_DELTA=
        BUILD102739I_ARGSOUT0_SENTINEL_MATCH_DELTA=
        BUILD102739I_ARGSOUT_TAIL_NULL_DELTA=
        BUILD102739I_HANDLER_RESULT_MATCH_DELTA=
        BUILD102739I_CONTROLLED_HANDLER_COMPLETE_DELTA=
        BUILD102739I_CONTROLLED_ACTION_HANDLER_ABI=PASS
        BUILD102739I_ORIGINAL_RETURN_PRESERVED=YES
        BUILD102739I_OBJECT_OWNERSHIP_UNCHANGED=YES
        BUILD102739I_REAL_JBROOT_HANDLER_INVOKED=NO
        BUILD102739I_REPLY_CREATED=NO
        BUILD102739I_BOOTSTRAP_TOUCHED=NO
    )
elif [[ "$RETURN_H" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739h_argument_telemetry'
    rg -q 'BUILD102739_IDENTITY_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739H_OBSERVER_MODE=READ_ONLY
        BUILD102739H_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739H_TRIGGER_PID=
        BUILD102739H_TRIGGER_EUID=
        BUILD102739H_TRIGGER_DOMAIN=
        BUILD102739H_TRIGGER_ACTION=
        BUILD102739H_TRIGGER_COUNT=1
        BUILD102739H_TRIGGER_TIMEOUT_GUARD_SECONDS=3
        BUILD102739H_TRIGGER_SEND_RC=
        BUILD102739H_ENTRY_DELTA=
        BUILD102739H_RETURN_DELTA=
        BUILD102739H_EXACT_CONTROLLED_PROBE_DELTA=
        BUILD102739H_DOMAIN_RESOLUTION_SUCCESS_DELTA=
        BUILD102739H_PERMISSION_ALLOW_DELTA=
        BUILD102739H_ACTION_RESOLUTION_SUCCESS_DELTA=
        BUILD102739H_HANDLER_INVOCATION_DELTA=
        BUILD102739H_HANDLER_POINTER_CAPTURE_DELTA=
        BUILD102739H_HANDLER_POINTER_NONNULL_DELTA=
        BUILD102739H_ARGS_ZERO_INITIALIZED_DELTA=
        BUILD102739H_ARGSOUT_ZERO_INITIALIZED_DELTA=
        BUILD102739H_ARG_DESCRIPTOR_SCAN_DELTA=
        BUILD102739H_ARG_NAME_ROOT_PATH_DELTA=
        BUILD102739H_ARG_TYPE_STRING_DELTA=
        BUILD102739H_ARG_DIRECTION_OUT_DELTA=
        BUILD102739H_OUTPUT_SLOT_BIND_DELTA=
        BUILD102739H_ARG_TERMINATOR_FOUND_DELTA=
        BUILD102739H_MARSHALLING_COMPLETE_DELTA=
        BUILD102739H_READ_ONLY_ACTION_ARGUMENT_MARSHALLING=PASS
        BUILD102739H_ORIGINAL_RETURN_PRESERVED=YES
        BUILD102739H_OBJECT_OWNERSHIP_UNCHANGED=YES
        BUILD102739H_HANDLER_INVOKED=NO
        BUILD102739H_REPLY_CREATED=NO
        BUILD102739H_BOOTSTRAP_TOUCHED=NO
    )
elif [[ "$RETURN_G" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739g_domain_action_telemetry'
    rg -q 'BUILD102739_IDENTITY_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739G_OBSERVER_MODE=READ_ONLY
        BUILD102739G_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739G_BOOTSTRAP_PORT_RC=
        BUILD102739G_BOOTSTRAP_PORT_VALID=
        BUILD102739G_BOOTSTRAP_PIPE_CREATED=
        BUILD102739G_TRIGGER_PID=
        BUILD102739G_TRIGGER_EUID=
        BUILD102739G_TRIGGER_DOMAIN=
        BUILD102739G_TRIGGER_ACTION=
        BUILD102739G_TRIGGER_COUNT=1
        BUILD102739G_TRIGGER_DICTIONARY_CREATED=
        BUILD102739G_TRIGGER_TIMEOUT_GUARD_SECONDS=3
        BUILD102739G_TRIGGER_SEND_ATTEMPTED=YES
        BUILD102739G_TRIGGER_SEND_RC=
        BUILD102739G_BASELINE_READ_RC=
        BUILD102739G_BASELINE_INVARIANTS=
        BUILD102739G_ENTRY_DELTA=
        BUILD102739G_RETURN_DELTA=
        BUILD102739G_SUCCESS_OBJECT_DELTA=
        BUILD102739G_EXACT_CONTROLLED_PROBE_DELTA=
        BUILD102739G_DOMAIN_RESOLUTION_ATTEMPT_DELTA=
        BUILD102739G_DOMAIN_RESOLUTION_SUCCESS_DELTA=
        BUILD102739G_PERMISSION_CHECK_DELTA=
        BUILD102739G_PERMISSION_ALLOW_DELTA=
        BUILD102739G_ACTION_NONZERO_DELTA=
        BUILD102739G_ACTION_RESOLUTION_ATTEMPT_DELTA=
        BUILD102739G_ACTION_RESOLUTION_SUCCESS_DELTA=
        BUILD102739G_HANDLER_INVOCATION_DELTA=
        BUILD102739G_TOKEN_PID_MATCH=
        BUILD102739G_TOKEN_EUID_MATCH=
        BUILD102739G_COUNTERS_MONOTONIC=
        BUILD102739G_DETERMINISTIC_INVOCATION=
        BUILD102739G_DETERMINISTIC_RETURN_PATH=
        BUILD102739G_GET_JBROOT_DESCRIPTOR_RESOLVED=YES
        BUILD102739G_READ_ONLY_DOMAIN_PERMISSION_ACTION_RESOLUTION=PASS
        BUILD102739G_ORIGINAL_RETURN_PRESERVED=YES
        BUILD102739G_OBJECT_OWNERSHIP_UNCHANGED=YES
    )
elif [[ "$RETURN_F" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739f_caller_identity_telemetry'
    rg -q 'BUILD102739F_CALLER_IDENTITY_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739F_OBSERVER_MODE=READ_ONLY
        BUILD102739F_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739F_BOOTSTRAP_PORT_RC=
        BUILD102739F_BOOTSTRAP_PORT_VALID=
        BUILD102739F_BOOTSTRAP_PIPE_CREATED=
        BUILD102739F_TRIGGER_PID=
        BUILD102739F_TRIGGER_EUID=
        BUILD102739F_TRIGGER_DOMAIN=
        BUILD102739F_TRIGGER_ACTION=
        BUILD102739F_TRIGGER_COUNT=1
        BUILD102739F_TRIGGER_DICTIONARY_CREATED=
        BUILD102739F_TRIGGER_TIMEOUT_GUARD_SECONDS=3
        BUILD102739F_TRIGGER_SEND_ATTEMPTED=YES
        BUILD102739F_TRIGGER_SEND_RC=
        BUILD102739F_BASELINE_READ_RC=
        BUILD102739F_BASELINE_INVARIANTS=
        BUILD102739F_ENTRY_DELTA=
        BUILD102739F_RETURN_DELTA=
        BUILD102739F_SUCCESS_OBJECT_DELTA=
        BUILD102739F_DICTIONARY_OBJECT_DELTA=
        BUILD102739F_DOMAIN_KEY_PRESENT_DELTA=
        BUILD102739F_ACTION_KEY_PRESENT_DELTA=
        BUILD102739F_DOMAIN_ACTION_ENVELOPE_DELTA=
        BUILD102739F_EXACT_CONTROLLED_PROBE_DELTA=
        BUILD102739F_DOMAIN_NONZERO_DELTA=
        BUILD102739F_SYSTEMWIDE_DOMAIN_CANDIDATE_DELTA=
        BUILD102739F_AUDIT_TOKEN_CAPTURE_DELTA=
        BUILD102739F_TOKEN_PID=
        BUILD102739F_TOKEN_EUID=
        BUILD102739F_TOKEN_PID_MATCH=
        BUILD102739F_TOKEN_EUID_MATCH=
        BUILD102739F_COUNTERS_MONOTONIC=
        BUILD102739F_DETERMINISTIC_INVOCATION=
        BUILD102739F_DETERMINISTIC_RETURN_PATH=
        BUILD102739F_READ_ONLY_CALLER_IDENTITY=
        BUILD102739F_ORIGINAL_RETURN_PRESERVED=YES
        BUILD102739F_OBJECT_OWNERSHIP_UNCHANGED=YES
    )
elif [[ "$RETURN_E" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739e_dictionary_telemetry'
    rg -q 'BUILD102739E_DICTIONARY_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739E_OBSERVER_MODE=READ_ONLY
        BUILD102739E_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739E_BOOTSTRAP_PORT_RC=
        BUILD102739E_BOOTSTRAP_PORT_VALID=
        BUILD102739E_BOOTSTRAP_PIPE_CREATED=
        BUILD102739E_TRIGGER_DICTIONARY_CREATED=
        BUILD102739E_TRIGGER_TIMEOUT_GUARD_SECONDS=3
        BUILD102739E_TRIGGER_SEND_ATTEMPTED=YES
        BUILD102739E_TRIGGER_SEND_RC=
        BUILD102739E_BASELINE_READ_RC=
        BUILD102739E_BASELINE_INVARIANTS=
        BUILD102739E_ENTRY_DELTA=
        BUILD102739E_RETURN_DELTA=
        BUILD102739E_SUCCESS_OBJECT_DELTA=
        BUILD102739E_DICTIONARY_OBJECT_DELTA=
        BUILD102739E_DOMAIN_KEY_PRESENT_DELTA=
        BUILD102739E_ACTION_KEY_PRESENT_DELTA=
        BUILD102739E_DOMAIN_ACTION_ENVELOPE_DELTA=
        BUILD102739E_EXACT_CONTROLLED_PROBE_DELTA=
        BUILD102739E_COUNTERS_MONOTONIC=
        BUILD102739E_DETERMINISTIC_INVOCATION=
        BUILD102739E_DETERMINISTIC_RETURN_PATH=
        BUILD102739E_READ_ONLY_DICTIONARY_CLASSIFICATION=
        BUILD102739E_ORIGINAL_RETURN_PRESERVED=YES
    )
elif [[ "$RETURN_D" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739c_output_telemetry'
    rg -q 'BUILD102739C_OUTPUT_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739C_OBSERVER_MODE=READ_ONLY
        BUILD102739C_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739D_BOOTSTRAP_PORT_RC=
        BUILD102739D_BOOTSTRAP_PORT_VALID=
        BUILD102739D_BOOTSTRAP_PIPE_CREATED=
        BUILD102739D_TRIGGER_DICTIONARY_CREATED=
        BUILD102739D_TRIGGER_TIMEOUT_GUARD_SECONDS=3
        BUILD102739D_TRIGGER_SEND_ATTEMPTED=YES
        BUILD102739D_TRIGGER_SEND_RC=
        BUILD102739D_BASELINE_READ_RC=
        BUILD102739D_BASELINE_INVARIANTS=
        BUILD102739D_ENTRY_DELTA=
        BUILD102739D_RETURN_DELTA=
        BUILD102739D_COUNTERS_MONOTONIC=
        BUILD102739D_DETERMINISTIC_INVOCATION=
        BUILD102739D_DETERMINISTIC_RETURN_PATH=
        BUILD102739D_OUTPUT_CONTRACT=
    )
elif [[ "$RETURN_C" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739c_output_telemetry'
    rg -q 'BUILD102739C_OUTPUT_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739C_OBSERVER_MODE=READ_ONLY
        BUILD102739C_REMOTE_DLOPEN_ATTEMPTED=NO
        BUILD102739C_REMOTE_WRITE_ATTEMPTED=NO
        BUILD102739C_POST_WALL2_OBSERVER_TASK_PORT=
        BUILD102739C_HOOK_UUID_MATCH=
        BUILD102739C_TELEMETRY_IN_WRITABLE_DATA=
        BUILD102739C_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739C_TELEMETRY_READ_RC=
        BUILD102739C_POST_WALL2_ENTRY_COUNT=
        BUILD102739C_POST_WALL2_RETURN_COUNT=
        BUILD102739C_SUCCESS_RETURN_COUNT=
        BUILD102739C_XOUT_ARGUMENT_COUNT=
        BUILD102739C_SUCCESS_XOUT_COUNT=
        BUILD102739C_SUCCESS_OBJECT_COUNT=
        BUILD102739C_COUNTER_INVARIANTS=
        BUILD102739C_FINAL_GOT_POINTER_MATCH=
        BUILD102739C_OUTPUT_CONTRACT_OBSERVED=
    )
elif [[ "$RETURN_B" == "1" ]]; then
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739b_return_telemetry'
    rg -q 'BUILD102739B_RETURN_TELEMETRY_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739B_OBSERVER_MODE=READ_ONLY
        BUILD102739B_REMOTE_DLOPEN_ATTEMPTED=NO
        BUILD102739B_REMOTE_WRITE_ATTEMPTED=NO
        BUILD102739B_POST_WALL2_OBSERVER_TASK_PORT=
        BUILD102739B_HOOK_UUID_MATCH=
        BUILD102739B_TELEMETRY_IN_WRITABLE_DATA=
        BUILD102739B_LAUNCHD_IMAGE_ADDRESS=
        BUILD102739B_WRAPPER_SYMBOL_ADDRESS=
        BUILD102739B_POST_WALL2_GOT_SLOT_ADDRESS=
        BUILD102739B_POST_WALL2_GOT_READ_RC=
        BUILD102739B_POST_WALL2_GOT_POINTER_MATCH=
        BUILD102739B_POLL_INTERVAL_US=
        BUILD102739B_POLL_ATTEMPT_LIMIT=
        BUILD102739B_POLL_ATTEMPTS_USED=
        BUILD102739B_BASELINE_RETURN_READ_RC=
        BUILD102739B_BASELINE_ENTRY_READ_RC=
        BUILD102739B_BASELINE_ENTRY_COUNT=
        BUILD102739B_BASELINE_RETURN_COUNT=
        BUILD102739B_RETURN_COUNT_READ_RC=
        BUILD102739B_ENTRY_COUNT_READ_RC=
        BUILD102739B_POST_WALL2_ENTRY_COUNT=
        BUILD102739B_POST_WALL2_RETURN_COUNT=
        BUILD102739B_FINAL_GOT_READ_RC=
        BUILD102739B_FINAL_GOT_POINTER_MATCH=
        BUILD102739B_RETURN_PATH_OBSERVED=
    )
else
    nm -g "$HOOK" 2>/dev/null | rg -q '_g_dt102739a_invocation_count'
    rg -q 'BUILD102739A_COUNTER_EXPORTED_YES' "$HOOK_STRINGS"
    REQUIRED_HELPER_MARKERS=(
        BUILD102739A_OBSERVER_MODE=READ_ONLY
        BUILD102739A_REMOTE_DLOPEN_ATTEMPTED=NO
        BUILD102739A_REMOTE_WRITE_ATTEMPTED=NO
        BUILD102739A_POST_WALL2_OBSERVER_TASK_PORT=
        BUILD102739A_HOOK_UUID_MATCH=
        BUILD102739A_COUNTER_IN_WRITABLE_DATA=
        BUILD102739A_POST_WALL2_INVOCATION_COUNT=
    )
fi
for marker in "${REQUIRED_HELPER_MARKERS[@]}"; do
    rg -q "$marker" "$HELPER_STRINGS"
done

"$LDID" -e "$HELPER" > "$OBJ/helper_entitlements.plist"
rg -q 'task_for_pid-allow' "$OBJ/helper_entitlements.plist"
rg -q 'platform-application' "$OBJ/helper_entitlements.plist"
rg -q 'com.apple.system-task-ports' "$OBJ/helper_entitlements.plist"
"$VTOOL" -show-build "$HELPER" | rg -q 'platform TVOS'

OBSERVER_DISASM="$OBJ/observer_disassembly.txt"
otool -tvV "$HELPER" | sed -n '/_dt102739a_observe_counter:/,/^_/p' > "$OBSERVER_DISASM"
rg -q '_getRemoteImageAddress' "$OBSERVER_DISASM"
rg -q '_remoteDlSym' "$OBSERVER_DISASM"
rg -q '_task_read' "$OBSERVER_DISASM"
if [[ "$RETURN_B" == "1" || "$RETURN_C" == "1" || "$RETURN_D" == "1" || "$RETURN_E" == "1" || "$RETURN_F" == "1" || "$RETURN_G" == "1" || "$RETURN_H" == "1" || "$RETURN_I" == "1" || "$RETURN_J" == "1" ]]; then
    rg -q '_usleep' "$OBSERVER_DISASM"
    rg -q '^#define DT102739B_LAUNCHD_GOT_OFFSET 0x65018ULL$' \
        "$PROJECT/handoff681/dt_opainject681_main.m"
    if [[ "$RETURN_J" == "1" ]]; then
        rg -q 'BUILD102739J_POST_WALL2_GOT_POINTER_MATCH=' "$HELPER_STRINGS"
    elif [[ "$RETURN_I" == "1" ]]; then
        rg -q 'BUILD102739I_POST_WALL2_GOT_POINTER_MATCH=' "$HELPER_STRINGS"
    elif [[ "$RETURN_H" == "1" ]]; then
        rg -q 'BUILD102739H_POST_WALL2_GOT_POINTER_MATCH=' "$HELPER_STRINGS"
    elif [[ "$RETURN_G" == "1" ]]; then
        echo "VARIANT=102739G"
        echo "SCOPE=READ_ONLY_DOMAIN_PERMISSION_ACTION_RESOLUTION"
        echo "TELEMETRY_RECORD_SIZE=192"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_ENVELOPE=IOS_JB_DOMAIN_ACTION_PLUS_UNIQUE_PROBE"
        echo "TRIGGER_DOMAIN=1"
        echo "TRIGGER_ACTION=1"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "XPC_OBJECT_OWNERSHIP_CHANGED=NO"
        echo "ORIGINAL_RETURN_VALUE_CHANGED=NO"
        echo "HANDLER_DISPATCH_ENABLED=NO"
        echo "REPLY_CREATION_ENABLED=NO"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_F" == "1" ]]; then
        rg -q 'BUILD102739F_POST_WALL2_GOT_POINTER_MATCH=' "$HELPER_STRINGS"
    elif [[ "$RETURN_E" == "1" ]]; then
        rg -q 'BUILD102739E_POST_WALL2_GOT_POINTER_MATCH=' "$HELPER_STRINGS"
    elif [[ "$RETURN_C" == "1" || "$RETURN_D" == "1" ]]; then
        rg -q 'BUILD102739C_POST_WALL2_GOT_POINTER_MATCH=' "$HELPER_STRINGS"
    else
        rg -q 'BUILD102739B_POST_WALL2_GOT_POINTER_MATCH=' "$HELPER_STRINGS"
    fi
fi
if rg -q '_injectDylibViaRop|_task_write|_mach_vm_write|_thread_create' "$OBSERVER_DISASM"; then
    echo "ERROR: remote mutation leaked into read-only observer function" >&2
    exit 1
fi

rm -f "$OUT"/BUILD102738*_RESOURCE_MANIFEST.txt "$OUT"/BUILD102739*_RESOURCE_MANIFEST.txt
if [[ "$RETURN_J" == "1" ]]; then
    VARIANT="102739J"
elif [[ "$RETURN_I" == "1" ]]; then
    VARIANT="102739I"
elif [[ "$RETURN_H" == "1" ]]; then
    VARIANT="102739H"
elif [[ "$RETURN_G" == "1" ]]; then
    VARIANT="102739G"
elif [[ "$RETURN_F" == "1" ]]; then
    VARIANT="102739F"
elif [[ "$RETURN_E" == "1" ]]; then
    VARIANT="102739E"
elif [[ "$RETURN_D" == "1" ]]; then
    VARIANT="102739D"
elif [[ "$RETURN_C" == "1" ]]; then
    VARIANT="102739C"
elif [[ "$RETURN_B" == "1" ]]; then
    VARIANT="102739B"
else
    VARIANT="102739A"
fi
{
    echo "CFBundleVersion=102738"
    if [[ "$RETURN_J" == "1" ]]; then
        echo "VARIANT=102739J"
        echo "SCOPE=CONTROLLED_REPLY_ROUNDTRIP"
        echo "TELEMETRY_RECORD_SIZE=584"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_DOMAIN=1"
        echo "TRIGGER_ACTION=1"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "CONTROLLED_HANDLER_ARGUMENT_COUNT=8"
        echo "CONTROLLED_HANDLER_ENABLED=YES"
        echo "STATIC_SENTINEL_OUTPUT=YES"
        echo "REPLY_CREATION_ENABLED=YES"
        echo "REPLY_SEND_ENABLED=YES"
        echo "CLIENT_REPLY_VALIDATION_ENABLED=YES"
        echo "COMMITTED_INPUT_CONSUME_ENABLED=YES"
        echo "COMMITTED_RETURN_VALUE=22"
        echo "REAL_JBROOT_HANDLER_ENABLED=NO"
        echo "BOOTSTRAP_CHANGED=NO"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_I" == "1" ]]; then
        echo "VARIANT=102739I"
        echo "SCOPE=CONTROLLED_ACTION_HANDLER_ABI"
        echo "TELEMETRY_RECORD_SIZE=352"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_DOMAIN=1"
        echo "TRIGGER_ACTION=1"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "CONTROLLED_HANDLER_ARGUMENT_COUNT=8"
        echo "CONTROLLED_HANDLER_ENABLED=YES"
        echo "REAL_JBROOT_HANDLER_ENABLED=NO"
        echo "STATIC_SENTINEL_OUTPUT=YES"
        echo "XPC_OBJECT_OWNERSHIP_CHANGED=NO"
        echo "ORIGINAL_RETURN_VALUE_CHANGED=NO"
        echo "REPLY_CREATION_ENABLED=NO"
        echo "BOOTSTRAP_CHANGED=NO"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_H" == "1" ]]; then
        echo "VARIANT=102739H"
        echo "SCOPE=READ_ONLY_ACTION_ARGUMENT_MARSHALLING"
        echo "TELEMETRY_RECORD_SIZE=280"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_ENVELOPE=IOS_JB_DOMAIN_ACTION_PLUS_UNIQUE_PROBE"
        echo "TRIGGER_DOMAIN=1"
        echo "TRIGGER_ACTION=1"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "ARGUMENT_DESCRIPTOR_COUNT=1"
        echo "ARGUMENT_DESCRIPTOR_NAME=root-path"
        echo "ARGUMENT_DESCRIPTOR_TYPE=JBS_TYPE_STRING"
        echo "ARGUMENT_DESCRIPTOR_DIRECTION=OUT"
        echo "OUTPUT_SLOT_BINDING_ENABLED=YES"
        echo "XPC_OBJECT_OWNERSHIP_CHANGED=NO"
        echo "ORIGINAL_RETURN_VALUE_CHANGED=NO"
        echo "JBSERVER_ENABLED=NO"
        echo "HANDLER_DISPATCH_ENABLED=NO"
        echo "REPLY_CREATION_ENABLED=NO"
        echo "BOOTSTRAP_CHANGED=NO"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_G" == "1" ]]; then
        echo "VARIANT=102739G"
        echo "SCOPE=READ_ONLY_DOMAIN_PERMISSION_ACTION_RESOLUTION"
        echo "TELEMETRY_RECORD_SIZE=192"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_ENVELOPE=IOS_JB_DOMAIN_ACTION_PLUS_UNIQUE_PROBE"
        echo "TRIGGER_DOMAIN=1"
        echo "TRIGGER_ACTION=1"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "SHADOW_DOMAIN_TABLE_ENABLED=YES"
        echo "PERMISSION_CHECK_ENABLED=YES"
        echo "SHADOW_ACTION_RESOLUTION_ENABLED=YES"
        echo "XPC_OBJECT_OWNERSHIP_CHANGED=NO"
        echo "ORIGINAL_RETURN_VALUE_CHANGED=NO"
        echo "JBSERVER_ENABLED=NO"
        echo "HANDLER_DISPATCH_ENABLED=NO"
        echo "REPLY_CREATION_ENABLED=NO"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_F" == "1" ]]; then
        echo "VARIANT=102739F"
        echo "SCOPE=READ_ONLY_CALLER_IDENTITY"
        echo "TELEMETRY_RECORD_SIZE=128"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_ENVELOPE=IOS_JB_DOMAIN_ACTION_PLUS_UNIQUE_PROBE"
        echo "TRIGGER_DOMAIN=1"
        echo "TRIGGER_ACTION=1"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "XPC_OBJECT_OWNERSHIP_CHANGED=NO"
        echo "ORIGINAL_RETURN_VALUE_CHANGED=NO"
        echo "JBSERVER_ENABLED=NO"
        echo "HANDLER_DISPATCH_ENABLED=NO"
        echo "REPLY_CREATION_ENABLED=NO"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_E" == "1" ]]; then
        echo "VARIANT=102739E"
        echo "SCOPE=READ_ONLY_POST_ORIGINAL_XPC_DICTIONARY_CLASSIFICATION"
        echo "TELEMETRY_RECORD_SIZE=88"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_ENVELOPE=IOS_JB_DOMAIN_ACTION_PLUS_UNIQUE_PROBE"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "XPC_OBJECT_OWNERSHIP_CHANGED=NO"
        echo "ORIGINAL_RETURN_VALUE_CHANGED=NO"
        echo "JBSERVER_ENABLED=NO"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_D" == "1" ]]; then
        echo "VARIANT=102739D"
        echo "SCOPE=DETERMINISTIC_POST_WALL2_LAUNCHD_XPC_TRIGGER"
        echo "HOOK_BINARY_REUSED_EXACTLY_FROM=102739C"
        echo "TELEMETRY_RECORD_SIZE=48"
        echo "TRIGGER_TRANSPORT=TASK_BOOTSTRAP_PORT_XPC_PIPE"
        echo "TRIGGER_REQUEST_COUNT=1"
        echo "TRIGGER_ENVELOPE=IOS_JB_DOMAIN_ACTION"
        echo "REMOTE_DLOPEN=NO"
        echo "REMOTE_WRITE=NO"
    elif [[ "$RETURN_C" == "1" ]]; then
        echo "VARIANT=102739C"
        echo "SCOPE=POST_WALL2_XPC_OUTPUT_CONTRACT_OBSERVATION"
        echo "TELEMETRY_RECORD_SIZE=48"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "BOUNDED_POLL_INTERVAL_US=20000"
        echo "BOUNDED_POLL_ATTEMPTS=100"
        echo "GUARDED_XOUT_DEREFERENCE=YES"
        echo "XPC_API_CALLS=NO"
    elif [[ "$RETURN_B" == "1" ]]; then
        echo "VARIANT=102739B"
        echo "SCOPE=POST_WALL2_ORIGINAL_RETURN_PATH_OBSERVATION"
        echo "TELEMETRY_RECORD_SIZE=16"
        echo "TELEMETRY_READ_ORDER=RETURN_THEN_ENTRY"
        echo "POST_WALL2_GOT_REVALIDATION=YES"
        echo "POST_WALL2_GOT_OFFSET=0x65018"
        echo "BOUNDED_POLL_INTERVAL_US=20000"
        echo "BOUNDED_POLL_ATTEMPTS=100"
        echo "MESSAGE_OR_XOUT_DEREFERENCE=NO"
    else
        echo "VARIANT=102739A"
        echo "SCOPE=POST_WALL2_READ_ONLY_WRAPPER_INVOCATION_OBSERVATION"
    fi
    echo "FUNCTIONAL_GATE_REUSED=102738"
    echo "SHARED_TELEMETRY_FILE=NO"
    echo "OBSERVER_REMOTE_DLOPEN=NO"
    echo "OBSERVER_REMOTE_WRITE=NO"
    for file in launchdhook516.dylib libjailbreak.dylib libchoma.dylib dt_jbctl516 dt_opainject516; do
        echo "$file=$(shasum -a 256 "$OUT/$file" | awk '{print $1}')"
    done
    echo "app_framework_libjailbreak.dylib=$(shasum -a 256 "$BUILD_ROOT/Frameworks/libjailbreak.dylib" | awk '{print $1}')"
} > "$OUT/BUILD${VARIANT}_RESOURCE_MANIFEST.txt"

echo "BUILD${VARIANT}_HOOK_EXPORT_AUDIT=PASS"
echo "BUILD${VARIANT}_HELPER_READ_ONLY_BRANCH_AUDIT=PASS"
echo "BUILD${VARIANT}_FROZEN_RESOURCES=PASS"
echo "BUILD${VARIANT}_HOOK_SHA256=$(shasum -a 256 "$HOOK" | awk '{print $1}')"
echo "BUILD${VARIANT}_HELPER_SHA256=$(shasum -a 256 "$HELPER" | awk '{print $1}')"
