#!/bin/bash
# Generate MAIN D0 canonical-identity pins from packaged Handoff516 Mach-Os.
# Pins are TrollStore signature-invariant (see tools/rootless_macho_canonical_id.py).
set -euo pipefail

SCRIPT="$(cd "$(dirname "$0")" && pwd -P)"
# shellcheck source=scripts/clean_project_env.sh
source "$SCRIPT/clean_project_env.sh"
KFD="$DT_KFD_ROOT"
HANDOFF="${ROOTLESS_R24_HANDOFF_DIR:-$DT_BUILD_ROOT/build/rootless_r4/Handoff516}"
GEN_DIR="$KFD/generated"
OUT_H="$GEN_DIR/dt_rootless_r24_d0_expect.h"
OUT_TXT="$HANDOFF/ROOTLESS_R24_D0_EXPECT.txt"
HOOK="$HANDOFF/launchdhook516.dylib"
SH="$HANDOFF/systemhook.dylib"
CANON_PY="$DT_TOOLS_ROOT/rootless_macho_canonical_id.py"

[[ -f "$HOOK" ]] || { echo "ERROR: missing $HOOK (build Handoff before R24 MAIN)" >&2; exit 1; }
[[ -f "$SH" ]] || { echo "ERROR: missing $SH (build Handoff before R24 MAIN)" >&2; exit 1; }
[[ -f "$CANON_PY" ]] || { echo "ERROR: missing $CANON_PY" >&2; exit 1; }

HOOK_CANON="$(python3 "$CANON_PY" "$HOOK" | awk -F= '/^CANONICAL_SHA256=/{print $2; exit}')"
SH_CANON="$(python3 "$CANON_PY" "$SH" | awk -F= '/^CANONICAL_SHA256=/{print $2; exit}')"
HOOK_UUID="$(python3 "$CANON_PY" "$HOOK" | awk -F= '/^UUID=/{print $2; exit}')"
SH_UUID="$(python3 "$CANON_PY" "$SH" | awk -F= '/^UUID=/{print $2; exit}')"
HOOK_RAW="$(python3 "$CANON_PY" "$HOOK" | awk -F= '/^RAW_SHA256=/{print $2; exit}')"
SH_RAW="$(python3 "$CANON_PY" "$SH" | awk -F= '/^RAW_SHA256=/{print $2; exit}')"

[[ "$HOOK_CANON" =~ ^[0-9a-f]{64}$ ]] || { echo "ERROR: bad hook canonical: $HOOK_CANON" >&2; exit 2; }
[[ "$SH_CANON" =~ ^[0-9a-f]{64}$ ]] || { echo "ERROR: bad systemhook canonical: $SH_CANON" >&2; exit 2; }
[[ "$HOOK_UUID" =~ ^[0-9A-F-]{36}$ ]] || { echo "ERROR: bad hook uuid: $HOOK_UUID" >&2; exit 2; }
[[ "$SH_UUID" =~ ^[0-9A-F-]{36}$ ]] || { echo "ERROR: bad systemhook uuid: $SH_UUID" >&2; exit 2; }

mkdir -p "$GEN_DIR"
TMP_H="$(mktemp)"
cat >"$TMP_H" <<EOF
/* Auto-generated by scripts/generate_rootless_r24_d0_expect.sh — do not edit. */
#pragma once
#define ROOTLESS_R24_EXPECT_HOOK_CANONICAL_SHA256_HEX "${HOOK_CANON}"
#define ROOTLESS_R24_EXPECT_SYSTEMHOOK_CANONICAL_SHA256_HEX "${SH_CANON}"
#define ROOTLESS_R24_EXPECT_HOOK_UUID_STR "${HOOK_UUID}"
#define ROOTLESS_R24_EXPECT_SYSTEMHOOK_UUID_STR "${SH_UUID}"
EOF

CHANGED=0
if [[ ! -f "$OUT_H" ]] || ! cmp -s "$TMP_H" "$OUT_H"; then
  mv "$TMP_H" "$OUT_H"
  CHANGED=1
else
  rm -f "$TMP_H"
fi

cat >"$OUT_TXT" <<EOF
ROOTLESS_R24_EXPECT_HOOK_CANONICAL_SHA256=${HOOK_CANON}
ROOTLESS_R24_EXPECT_SYSTEMHOOK_CANONICAL_SHA256=${SH_CANON}
ROOTLESS_R24_EXPECT_HOOK_UUID=${HOOK_UUID}
ROOTLESS_R24_EXPECT_SYSTEMHOOK_UUID=${SH_UUID}
ROOTLESS_R24_IPA_HOOK_RAW_SHA256=${HOOK_RAW}
ROOTLESS_R24_IPA_SYSTEMHOOK_RAW_SHA256=${SH_RAW}
ROOTLESS_R24_D0_IDENTITY_KIND=CANONICAL_MACHO_TS_INVARIANT
EOF

if [[ "$CHANGED" -eq 1 ]]; then
  touch "$KFD/dt_kcall_planb.m"
fi

echo "ROOTLESS_R24_D0_EXPECT_HOOK_CANONICAL_SHA256=${HOOK_CANON}"
echo "ROOTLESS_R24_D0_EXPECT_SYSTEMHOOK_CANONICAL_SHA256=${SH_CANON}"
echo "ROOTLESS_R24_D0_EXPECT_HOOK_UUID=${HOOK_UUID}"
echo "ROOTLESS_R24_D0_EXPECT_SYSTEMHOOK_UUID=${SH_UUID}"
echo "ROOTLESS_R24_D0_EXPECT_HEADER=${OUT_H}"
