#!/usr/bin/env python3
"""Emit generated/dt_rootless_r24_dyld_identity.h from the frozen Phase-2 dyld artifact."""
from __future__ import annotations

import hashlib
import json
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
from r24_dyld_contract import (  # noqa: E402
    GENERATED_PATCH_BYTES,
    GENERATED_PATCH_OFFSET,
    JBINFO_SECTION_SIZE,
    bytes_at_offset,
    jbinfo_section_size,
    runtime_dyld_layout,
)
from rootless_macho_canonical_id import CanonicalIdError, canonical_sha256, macho_uuid  # noqa: E402


def extract_identity_for_header(dyld: Path, manifest: dict) -> dict[str, str]:
    layout = runtime_dyld_layout(dyld)
    patch = bytes_at_offset(dyld, GENERATED_PATCH_OFFSET, len(GENERATED_PATCH_BYTES) // 2)
    if patch.hex() != GENERATED_PATCH_BYTES:
        raise CanonicalIdError("patch bytes mismatch")
    jbinfo = jbinfo_section_size(dyld)
    if jbinfo != JBINFO_SECTION_SIZE:
        raise CanonicalIdError("__jbinfo size mismatch")
    canon = canonical_sha256(dyld)
    raw = hashlib.sha256(dyld.read_bytes()).hexdigest()
    uid = macho_uuid(dyld)
    out = {
        "CANONICAL_SHA256": canon,
        "RAW_SHA256": raw,
        "UUID": uid,
        "GENERATED_PATCH_OFFSET": manifest.get("generated_patch_offset", f"0x{GENERATED_PATCH_OFFSET:x}"),
        "LAYOUT_NCMDS": str(layout["NCMDS"]),
        "LAYOUT_CS_OFF": str(layout["CS_OFF"]),
        "LAYOUT_MAX_NON_SIGNATURE_END": str(layout["MAX_NON_SIGNATURE_END"]),
    }
    man_canon = manifest.get("generated_canonical_sha256")
    if man_canon and man_canon != canon:
        raise CanonicalIdError(f"manifest canonical mismatch: manifest={man_canon} dyld={canon}")
    return out


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: generate_r24_dyld_identity_header.py <dyld> <manifest.json> <out.h>", file=sys.stderr)
        return 2
    dyld = Path(sys.argv[1])
    manifest = json.loads(Path(sys.argv[2]).read_text())
    out_h = Path(sys.argv[3])
    contract = extract_identity_for_header(dyld, manifest)
    u = uuid.UUID(contract["UUID"])
    ub = u.bytes
    lines = [
        "/* Auto-generated by scripts/generate_r24_dyld_identity_header.py — do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "#define ROOTLESS_R24_DYLD_IDENTITY_GENERATED 1",
        f'#define ROOTLESS_R24_GENERATED_DYLD_CANONICAL_SHA256_HEX "{contract["CANONICAL_SHA256"]}"',
        f'#define ROOTLESS_R24_GENERATED_DYLD_RAW_SHA256_HEX "{contract["RAW_SHA256"]}"',
        f'#define ROOTLESS_R24_GENERATED_DYLD_UUID_STR "{contract["UUID"]}"',
        f'#define ROOTLESS_R24_STOCK_DYLD_SHA256_HEX "{manifest["source_sha256"]}"',
        f'#define ROOTLESS_R24_STOCK_PATCH_OFFSET {manifest["stock_patch_offset"]}',
        f'#define ROOTLESS_R24_GENERATED_PATCH_OFFSET {manifest["generated_patch_offset"]}',
        f'#define ROOTLESS_R24_GENERATED_PATCH_BYTES_HEX "{manifest["patch"]}"',
        f'#define ROOTLESS_R24_STOCK_PATCH_PROLOGUE_HEX "{manifest["verified_prologue"]}"',
        f"#define ROOTLESS_R24_JBINFO_SECTION_SIZE {JBINFO_SECTION_SIZE}",
        f'#define ROOTLESS_R24_GENERATED_DYLD_NCMDS {contract["LAYOUT_NCMDS"]}',
        f'#define ROOTLESS_R24_GENERATED_DYLD_CS_OFF {contract["LAYOUT_CS_OFF"]}',
        f'#define ROOTLESS_R24_GENERATED_DYLD_MAX_NON_SIGNATURE_END {contract["LAYOUT_MAX_NON_SIGNATURE_END"]}',
        "static const uint8_t ROOTLESS_R24_GENERATED_DYLD_UUID[16] = {",
        "    " + ", ".join(f"0x{b:02x}" for b in ub) + "",
        "};",
    ]
    out_h.parent.mkdir(parents=True, exist_ok=True)
    out_h.write_text("\n".join(lines) + "\n")
    print(f"ROOTLESS_R24_DYLD_IDENTITY_HEADER={out_h}")
    print(f"ROOTLESS_R24_GENERATED_DYLD_CANONICAL_SHA256_HEX={contract['CANONICAL_SHA256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
