#!/bin/bash
# Pack NitroTV seed archive — full build source + gates + IPAs + device logs
# Target: <= 100MB zip for private GitHub (excludes non-build blobs only)
set -euo pipefail

BUILD_ROOT="$(cd "$(dirname "$0")/../.." && pwd -P)"
PROJECT="$(cd "$(dirname "$0")/.." && pwd -P)"
DESKTOP_WS="/Users/dxcool223/Desktop/untitled folder 4"
POC_SRC="${POC_SRC:-$DESKTOP_WS/everything we traced in ida pro + others /untitled folder 2/run 1/poc.txt}"
STABLE656="$BUILD_ROOT/stable102656-direct-helper-pipe-pass-2026-07-03"
MAX_ZIP_BYTES=$((100 * 1024 * 1024))

ARCHIVE_NAME="nitrotv-seed-direct-jbroot-helper-102660-2026-07-03"
STAGING="$BUILD_ROOT/$ARCHIVE_NAME"
OUT_ZIP="$BUILD_ROOT/${ARCHIVE_NAME}.zip"

rm -rf "$STAGING"
mkdir -p "$STAGING/artifacts" "$STAGING/device-logs" "$STAGING/gates"

echo "=== sync gate docs 649-660 ==="
shopt -s nullglob
for base in "$PROJECT/docs/audits-ida" "$DESKTOP_WS/dopamin-tvOS-kfd/docs/audits-ida"; do
    [[ -d "$base" ]] || continue
    for f in "$base"/BUILD102649_*.txt "$base"/BUILD102650_*.txt "$base"/BUILD102651_*.txt \
             "$base"/BUILD102652_*.txt "$base"/BUILD102653_*.txt "$base"/BUILD102654_*.txt \
             "$base"/BUILD102655_*.txt "$base"/BUILD102656_*.txt "$base"/BUILD102658_*.txt \
             "$base"/BUILD102659_*.txt "$base"/BUILD102660_*.txt; do
        [[ -f "$f" ]] && cp "$f" "$STAGING/gates/"
    done
done
shopt -u nullglob

echo "=== copy IPAs ==="
for ipa in build102.6.56.ipa build102.6.59.ipa; do
    if [[ -f "$BUILD_ROOT/$ipa" ]]; then
        cp "$BUILD_ROOT/$ipa" "$STAGING/artifacts/"
    elif [[ -f "$DESKTOP_WS/$ipa" ]]; then
        cp "$DESKTOP_WS/$ipa" "$STAGING/artifacts/"
    else
        echo "WARN: missing $ipa"
    fi
done

echo "=== device logs ==="
if [[ -f "$POC_SRC" ]]; then
    cp "$POC_SRC" "$STAGING/device-logs/poc-device-run-659-capability-2026-07-03.txt"
    grep -E 'KCALL653|KCALL658|HELPER_|dt_direct653|==> container|Sandbox: dt_direct653' \
        "$POC_SRC" > "$STAGING/device-logs/poc-kcall658-capability-extract-2026-07-03.txt" || true
fi
if [[ -f "$STABLE656/poc-kcall653-pass-2026-07-03.txt" ]]; then
    cp "$STABLE656/poc-kcall653-pass-2026-07-03.txt" "$STAGING/device-logs/"
fi
if [[ -f "$STABLE656/poc-device-run-2026-07-03.txt" ]]; then
    cp "$STABLE656/poc-device-run-2026-07-03.txt" "$STAGING/device-logs/poc-device-run-656-pipe-pass-2026-07-03.txt"
fi

echo "=== copy README ==="
cp "$PROJECT/README_NITROTV_SEED.md" "$STAGING/"

cat > "$STAGING/SEED_EXCLUSIONS.txt" <<'EOF'
SEED EXCLUSIONS (GitHub <= 100MB) — not removed from main dev tree
==================================================================
These are omitted from the seed zip only. Build + 653-route handoff do NOT need them.

Dopamine_Rootful-main/Application/Dopamine.zip
  Prebuilt iOS app bundle zip (~51MB). Makefile uses Application/Dopamine source only.

dopamin-tvOS-kfd/docs/audits-ida/binaries/
  IDA databases + OTA Mach-O extracts (~52MB). Gate text docs remain in gates/ and
  docs/audits-ida/BUILD102649_*.txt … BUILD102660_*.txt.

Build artifacts (regenerated by make ipa):
  .theos/ · layout/Payload/ · *.ipa in source root · ida_extras/ · external-static-src/

Symlink loops:
  Dopamine_Rootful-main/Dopamine_Rootful-main (self-reference)

Everything required to compile and continue BUILD102661 is still included.
EOF

echo "=== rsync Dopamine_Rootful-main ==="
rsync -a \
    --safe-links \
    --exclude '.git' --exclude '.DS_Store' \
    --exclude 'Dopamine_Rootful-main' \
    --exclude 'Application/Dopamine.zip' \
    --exclude 'Application/Dopamine/Resources/*.deb' \
    "$BUILD_ROOT/Dopamine_Rootful-main/" "$STAGING/Dopamine_Rootful-main/"

echo "=== rsync dopamin-tvOS-kfd source ==="
rsync -a \
    --safe-links \
    --exclude '.theos' \
    --exclude '.DS_Store' \
    --exclude 'layout/Payload' \
    --exclude 'build/' \
    --exclude 'build-tvos-static/' \
    --exclude 'external-static-src/' \
    --exclude 'ida_extras/' \
    --exclude 'docs/audits-ida/binaries/' \
    --exclude 'dopamin-tvOS-kfd' \
    --exclude '*.ipa' \
    --exclude "$ARCHIVE_NAME" \
    "$PROJECT/" "$STAGING/dopamin-tvOS-kfd/"

echo "=== sync gates into source docs/audits-ida ==="
mkdir -p "$STAGING/dopamin-tvOS-kfd/docs/audits-ida"
cp "$STAGING/gates"/BUILD102*.txt "$STAGING/dopamin-tvOS-kfd/docs/audits-ida/"

echo "=== ARCHIVE_MANIFEST.txt ==="
{
    echo "ARCHIVE: $ARCHIVE_NAME"
    echo "DATE: $(date +%Y-%m-%d)"
    echo "VERDICT: PHASE3_STABLE_PASS + KCALL658_CAPABILITY_MAP_OK"
    echo "CURRENT_IPA: artifacts/build102.6.59.ipa (CFBundleVersion 102659)"
    echo "CHECKPOINT_IPA: artifacts/build102.6.56.ipa (CFBundleVersion 102656)"
    echo "MAX_ZIP_BYTES: $MAX_ZIP_BYTES"
    echo ""
    echo "SHA256 (top-level + artifacts):"
    for f in README_NITROTV_SEED.md SEED_EXCLUSIONS.txt artifacts/build102.6.56.ipa artifacts/build102.6.59.ipa; do
        [[ -f "$STAGING/$f" ]] && shasum -a 256 "$STAGING/$f"
    done
    echo ""
    echo "SHA256 (all files):"
    (cd "$STAGING" && find . -type f ! -name 'ARCHIVE_MANIFEST.txt' | sort | while read -r f; do
        h=$(shasum -a 256 "$f" | awk '{print $1}')
        printf '%s  %s\n' "$h" "${f#./}"
    done)
} > "$STAGING/ARCHIVE_MANIFEST.txt"

echo "=== zip (max compression) ==="
rm -f "$OUT_ZIP"
(
    cd "$BUILD_ROOT"
    zip -9 -qr "$OUT_ZIP" "$ARCHIVE_NAME" -x "*.DS_Store" -x "**/.DS_Store"
)
rm -rf "$STAGING"

ZIP_BYTES=$(stat -f%z "$OUT_ZIP" 2>/dev/null || stat -c%s "$OUT_ZIP")
echo "=== done ==="
ls -lh "$OUT_ZIP"
shasum -a 256 "$OUT_ZIP"
echo "ZIP_BYTES=$ZIP_BYTES MAX=$MAX_ZIP_BYTES"
if (( ZIP_BYTES > MAX_ZIP_BYTES )); then
    echo "ERROR: zip exceeds 100MB limit ($ZIP_BYTES bytes)" >&2
    exit 1
fi
echo "OUT_ZIP=$OUT_ZIP"
